name: Analyze Repository

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'GitHub Repository URL to analyze'
        required: true
      model:
        description: 'AI model (e.g., sonnet, gpt-4, gemini)'
        default: 'claude-sonnet'
      config_file:
        description: 'Optional config file path (TOML/YAML/JSON)'
        default: ''
  workflow_call:
    inputs:
      repo_url:
        description: 'GitHub Repository URL to analyze'
        required: true
        type: string
      model:
        description: 'AI model to use'
        default: 'sonnet'
        type: string
      config_file:
        description: 'Optional config file path'
        default: ''
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for API access'
        required: false
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for Claude models'
        required: false
      OPENAI_API_KEY:
        description: 'OpenAI API key for GPT models'
        required: false
      GOOGLE_API_KEY:
        description: 'Google API key for Gemini models'
        required: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: apt-get update && apt-get install -y jq

      - name: Run analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: .github/scripts/run_repo_analyzer.sh "${{ inputs.repo_url }}" "${{ inputs.model }}" "${{ inputs.config_file }}"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: output/
          retention-days: 7
